# meta.yaml is configuration for the tool conda-build.
#
# meta.yaml reference:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
#
{% set name = "dask-gateway" %}
{% set version = "2022.4.0" %}



# Common configuration for dask-gateway and dask-gateway-server outputs
# -----------------------------------------------------------------------------
package:
  version: {{ version }}
  name: {{ name|lower }}

source:
  url: https://github.com/dask/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3c79b1458e5c52f8b875332a75c034a62bb1563b650eac14f4e9cea1a217e6e6

build:
  number: 0



# Specific configuration for outputs beyond the common configuration above
# -----------------------------------------------------------------------------
outputs:
  - name: dask-gateway
    build:
      noarch: python
      script: >-
        cd dask-gateway &&
        python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway/requirements.txt
        #
        - aiohttp
        - click
        - dask >=2.2.0
        - distributed >=2021.01.1
        - pyyaml
        - tornado
    test:
      imports:
        - dask_gateway

  - name: dask-gateway-server
    build:
      script: >-
        cd dask-gateway-server &&
        python -m pip install . -vv --no-deps
      # entry_points below should match entry_points in setup.py:
      # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py
      #
      entry_points:
        - dask-gateway-server = dask_gateway_server.app:main
        - dask-gateway-jobqueue-launcher = dask_gateway_server.backends.jobqueue.launcher:main
    requirements:
      build:
        - {{ compiler('go') }}
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/requirements.txt
        #
        - aiohttp
        - colorlog
        - cryptography
        - traitlets
    test:
      imports:
        - dask_gateway_server
      commands:
        - dask-gateway-server --help
        - which dask-gateway-jobqueue-launcher


  # Client-side kerberos auth
  - name: dask-gateway-kerberos
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway', exact=True) }}
        - pykerberos  # [osx or linux]
        - winkerberos  # [win]
    test:
      imports:
        - dask_gateway


  # Kerberos authentication
  - name: dask-gateway-server-kerberos
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway-server', exact=True) }}
        - pykerberos
    test:
      imports:
        - dask_gateway_server

  # Local backend
  - name: dask-gateway-server-local
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway-server', exact=True) }}
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.local

  # Jobqueue backends
  - name: dask-gateway-server-jobqueue
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway-server', exact=True) }}
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.jobqueue.slurm
        - dask_gateway_server.backends.jobqueue.pbs

  # Hadoop YARN backend
  - name: dask-gateway-server-yarn
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway-server', exact=True) }}
        - sqlalchemy
        - skein >=0.7.3
    test:
      imports:
        - dask_gateway_server.backends.yarn

  # Kubernetes backend
  - name: dask-gateway-server-kubernetes
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - {{ pin_subpackage('dask-gateway-server', exact=True) }}
        - kubernetes_asyncio
    test:
      imports:
        - dask_gateway_server.backends.kubernetes




# Additional information
# -----------------------------------------------------------------------------

about:
  home: http://github.com/dask/dask-gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A multi-tenant server for securely deploying and managing Dask clusters.
  description: A multi-tenant server for securely deploying and managing Dask clusters.
  doc_url: https://gateway.dask.org
  dev_url: http://github.com/dask/dask-gateway

extra:
  # To add new maintainers, open an issue with a specific title as described in
  # https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list
  #
  recipe-maintainers:
    - consideRatio
    - jacobtomlinson
    - jcrist
    - martindurant
    - TomAugspurger
