# meta.yaml is configuration for the tool conda-build.
#
# meta.yaml reference:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
#
# Overall this configuration is tricky to understand, but here are some notes
# that can be helpful.
#
# - This file is influenced by variables set in conda_build_variants.yaml, such
#   as target_goos and target_goarch. Reading the documentation about that in
#   its entirety was essential to set this up.
#
# - This file is influenced by special helper functions, such as compiler() and
#   pin_subpackage(), for details about those see:
#   https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions.https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2-functions
#
{% set name = "dask-gateway" %}
{% set version = "2022.4.0" %}



# Common configuration for dask-gateway and dask-gateway-server outputs
# -----------------------------------------------------------------------------
package:
  version: {{ version }}
  name: {{ name|lower }}

source:
  url: https://github.com/dask/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3c79b1458e5c52f8b875332a75c034a62bb1563b650eac14f4e9cea1a217e6e6

build:
  number: 0



# Specific configuration for outputs beyond the common configuration above
# -----------------------------------------------------------------------------
outputs:
  # core package: server
  - name: dask-gateway-server
    build:
      # dask-gateway-server don't support windows, dask-gateway does
      #
      skip: true  # [target_platform == 'win-64']
      # script_env use target_goos and target_goarch, which comes in 2x2
      # combinations, so this output will be emitted four times. For more
      # details see the note about "build hash" in
      # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-section.
      #
      script_env:
        - GOOS=linux  # [target_platform == 'linux-64' or target_platform == 'linux-aarch64']
        - GOOS=darwin  # [target_platform == 'osx-64' or target_platform == 'osx-arm64']
        - GOARCH=amd64  # [target_platform == 'linux-64' or target_platform == 'osx-64']
        - GOARCH=arm64  # [target_platform == 'linux-aarch64' or target_platform == 'osx-arm64']
      script: >-
        echo GOOS=$GOOS &&
        echo GOARCH=$GOARCH &&
        cd dask-gateway-server &&
        python -m pip install . -vv --no-deps
      # entry_points below should match entry_points in setup.py:
      # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/setup.py
      #
      entry_points:
        - dask-gateway-server = dask_gateway_server.app:main
        - dask-gateway-jobqueue-launcher = dask_gateway_server.backends.jobqueue.launcher:main
    requirements:
      build:
        # This jinja function will expand to go_compiler and target_platform,
        # which then makes the build requirements change, which matters with
        # regards to the variations for this to be considered separate.
        #
        # For details about compiler(), see
        # https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#extra-jinja2.
        #
        - {{ compiler('go') }}
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/requirements.txt
        #
        - aiohttp
        - colorlog
        - cryptography
        - traitlets
    test:
      imports:
        - dask_gateway_server
      commands:
        - dask-gateway-server --help
        - which dask-gateway-jobqueue-launcher


  # core package: client
  - name: dask-gateway
    build:
      noarch: python
      script: >-
        cd dask-gateway &&
        python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Requirements below should match content of requirements.txt:
        # https://github.com/dask/dask-gateway/blob/main/dask-gateway/requirements.txt
        #
        - aiohttp
        - click
        - dask >=2.2.0
        - distributed >=2021.01.1
        - pyyaml
        - tornado
    test:
      imports:
        - dask_gateway



  # client: kerberos authentication
  - name: dask-gateway-kerberos
    requirements:
      run:
        - dask-gateway =={{ version }}
        - pykerberos  # [target_platform != 'win-64']
        - winkerberos  # [target_platform == 'win-64']
    test:
      imports:
        - dask_gateway

  # server: kerberos authentication
  - name: dask-gateway-server-kerberos
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server =={{ version }}
        - pykerberos
    test:
      imports:
        - dask_gateway_server

  # server: local backend
  - name: dask-gateway-server-local
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server =={{ version }}
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.local

  # server: jobqueue backends
  - name: dask-gateway-server-jobqueue
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server =={{ version }}
        - sqlalchemy
    test:
      imports:
        - dask_gateway_server
        - dask_gateway_server.backends.jobqueue.slurm
        - dask_gateway_server.backends.jobqueue.pbs

  # server: hadoop yarn backend
  - name: dask-gateway-server-yarn
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server =={{ version }}
        - sqlalchemy
        - skein >=0.7.3
    test:
      imports:
        - dask_gateway_server.backends.yarn

  # server: kubernetes backend
  - name: dask-gateway-server-kubernetes
    build:
      skip: true  # [target_platform == 'win-64']
    requirements:
      run:
        - dask-gateway-server =={{ version }}
        - kubernetes_asyncio
    test:
      imports:
        - dask_gateway_server.backends.kubernetes




# Additional information
# -----------------------------------------------------------------------------

about:
  home: http://github.com/dask/dask-gateway
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A multi-tenant server for securely deploying and managing Dask clusters.
  description: A multi-tenant server for securely deploying and managing Dask clusters.
  doc_url: https://gateway.dask.org
  dev_url: http://github.com/dask/dask-gateway

extra:
  # To add new maintainers, open an issue with a specific title as described in
  # https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list
  #
  recipe-maintainers:
    - consideRatio
    - jacobtomlinson
    - jcrist
    - martindurant
    - TomAugspurger
