# conda-forge.yml is configuration for the tool conda-smithy.
#
# conda-forge.yml reference:
# https://conda-forge.org/docs/maintainer/conda_forge_yml.html
#
# Rerender the feedstock if you make changes to this file. This can for example
# be done by commenting "@conda-forge-admin, please rerender" in a PR.
#
provider:
  linux_64: azure
  linux_aarch64: azure
  osx_64: azure
  win_64: none
  linux_ppc64le: None
build_with_mambabuild: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
