# conda-forge.yml is configuration for the tool conda-smithy.
#
# conda-forge.yml reference:
# https://conda-forge.org/docs/maintainer/conda_forge_yml.html
#
# Rerender the feedstock if you make changes to this file. This can for example
# be done by commenting "@conda-forge-admin, please rerender" in a PR or with:
#
#   conda-smithy rerender --commit auto
#

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#build-with-mambabuild
build_with_mambabuild: true

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#conda-forge-output-validation
conda_forge_output_validation: true

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#github
github:
  branch_name: main
  tooling_branch_name: main

# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#build-platform
#
# While we could cross compile 
#
build_platform:
  # target_platform: build_platform
  linux_64: linux_64
  linux_aarch64: linux_aarch64
  osx_64: osx_64
  # osx_arm64: 
  win_64: win_64

# provider for linux_aarch64 has to be set explicitly as it otherwise defaults
# to no provider.
#
# https://conda-forge.org/docs/maintainer/conda_forge_yml.html#provider
#
#
provider:
  # build_platform: provider of ci workers
  linux_64: default
  linux_aarch64: default
  osx_64: default
  # osx_arm64 isn't available
  win_64: default

test: native
